name: marquee
description: 'A Flutter widget that scrolls text infinitely. Provides many
  customizations including custom scroll directions, durations, curves as well
  as pauses after every round.'
version: 2.2.3
repository: https://github.com/MarcelGarus/marquee

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fading_edge_scrollview: 2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
